
package com.nico.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculadoraImpl", targetNamespace = "http://services.nico.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadoraImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcular", targetNamespace = "http://services.nico.com/", className = "com.nico.services.Calcular")
    @ResponseWrapper(localName = "calcularResponse", targetNamespace = "http://services.nico.com/", className = "com.nico.services.CalcularResponse")
    @Action(input = "http://services.nico.com/CalculadoraImpl/calcularRequest", output = "http://services.nico.com/CalculadoraImpl/calcularResponse")
    public double calcular(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
